name: A workflow for ensuring credentials are not in file
on: push
jobs:
  build:
    name: Cred Checker
    runs-on: ubuntu-latest
    steps:        
       - uses: actions/checkout@master
       - name: trufflehog-actions-scan
         uses: edplato/trufflehog-actions-scan@master
         with:
           branch: ${{ github.head_ref }}
           scanArguments: "--regex --max_depth=10  --rules /regexes.json"
           #test runs
       - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
         if: always()
         with:
           github-token: ${{ secrets.TOKEN}}
           webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}  
